### ISSUE TITLE
Can quit the Finder

### ISSUE THREAD

**Issue by 00dani** [dteoh/SlowQuitApps#4]
Normally if you hit ⌘Q while the desktop is focused, you just get an error sound and nothing happens. If you hit ⌘Q with SlowQuitApps running and the desktop focused, the Finder quits and your desktop vanishes.

It's not a huge problem - you can bring it back by clicking it in the dock - but it's a weird inconsistency and quitting the Finder isn't a good idea in any case.

**Comment by dteoh** [comment]
Fixed!

New binary published on the releases page.

**Comment by JayBrown** [comment]
Love this update! Thank you also @00dani for bringing this up. I had actually changed my Finder prefs to include ⌘Q for the Finder, because I sometimes need to `osascript -e 'tell application "Finder" to quit' instead of `killall Finder`, but I only need to use this from shell scripts, not as a keyboard command. Quitting still works when selecting "Quit Finder" from the menu bar; best solution for the Finder.
