### ISSUE TITLE
It's work fine on Mojave，but stop working everytime when I reboot the system.

### ISSUE THREAD

**Issue by niices** [dteoh/SlowQuitApps#44]
I can find it in Activity Monitor.app.
![image](https://user-images.githubusercontent.com/8327775/47702609-769c7d00-dc58-11e8-94de-06803117b080.png)
But it doesn't work anymore.
Cmd+Q also lose it's function.
And it's work when I quit it on Activity Monitor.app and restart.

**Comment by pedromartinez11** [comment]
It's happening for me too. I installed with homebrew.

**Comment by Shagon94** [comment]
After installing it and running it adds an entry to auto start, however, restarting the device makes the app to break - as running it again prompts us with a "do you wish to autorun" screen once more

**Comment by elder-cb** [comment]
It stops working also after hibernation, not only a reboot :(
I guess it's the same issue, though :)

**Comment by JayBrown** [comment]
Have you codesigned SlowQuitApps, and have you added it to the Accessibility list in System Preferences > Security & Privacy > Privacy?

Mojave's TCC doesn't seem behave well with unsigned processes, i.e. it will ask for permissions again and again, and maybe that breaks SlowQuitApps at login and wake-from-safesleep. I noticed this with my own AppleScript apps, and once I codesigned them, it works fine. (You can use any self-issued code-signing certificate; an Apple Developer ID Applications certificiate is not needed; maybe ad-hoc signing also works, but I haven't tried that yet.)

I've just tested shutting down my Mac, and rebooting, and SlowQuitApps v0.6.0 loads fine at login, and works as it should, although we still have the [alert sound bug](https://github.com/dteoh/SlowQuitApps/issues/45), so I'll have to revert to v0.5.0 nonetheless.

(Mojave 10.14.1)

**Comment by dteoh** [comment]
The codesign system is quite frustrating and designed to extract (extort?) money first, and add security second. If Apple was serious about security, macOS devs should be able to get a Developer ID certificate for free or at a very reduced price. I don't want to pay for extra services (Mac and iOS App Store publishing) that I will not use. I suspect however, that I will be forced to pay the fee if a working solution cannot be found.

> I'm actually using a self-issued certificate chain, complete with Root CA and intermediate certificate, following the Apple Developer ID naming scheme to the letter. 

I don't think anyone is going to want to install a Root CA from a random dev on the internet to use an app. Especially when the app in question is a (benevolent) keylogger.

> Maybe ad-hoc signing also works, but I haven't tried that yet.

It doesn't when I tried it, but it could just be that I didn't tick the magic combination of compiler flags + Xcode buttons.

> just tested a second reboot (without shutdown), and SlowQuitApps loads fine at login & works properly

Start on login is pretty much in a weird half-broken state because the API that I was using to add SQA to system startup is pretty much deprecated/gone. The new way to do it involves registering a helper app whose job is to start the main app.

**Comment by JayBrown** [comment]
> Start on login is pretty much in a weird half-broken state because the API that I was using to add SQA to system startup is pretty much deprecated/gone. The new way to do it involves registering a helper app whose job is to start the main app.

Yes, that might have been what caused the latest [problems with Firefox](https://github.com/dteoh/SlowQuitApps/issues/47). I have a login script running anyway, so I've added `open -a "SlowQuitApps"` to the script and removed it from my login items in System Preferences; let's see how that goes.

> I don't think anyone is going to want to install a Root CA from a random dev on the internet to use an app. Especially when the app in question is a (benevolent) keylogger.

Right. That's why it's better that the user creates his own certificate (chain) for these purposes, so there is no CA trust issue in the first place.

As for code signing in general, I believe Apple should give *every user* a code-signing certificate, but one that is by default only trusted on the local machine. That would be fine for unsigned applications. Users just codesign them themselves with a little helper app provided by a third-party or even Apple, with required admin privileges (root) for protection against malware signing itself with the user's certificate, and then the app will run fine locally, but if they copy the app to another computer, it would need to be codesigned for that machine afresh. Just my 2¢.

**Comment by dteoh** [comment]
Please give v0.7.0 a go, it *might* fix this issue...

**Comment by mstnorris** [comment]
@dteoh the v0.7.0 update is working for me after initial install. I'll report back should I notice anything strange after a reboot but all OK so far. Thanks.

**Comment by JayBrown** [comment]
Good luck. Not working for me.

**Comment by wizonesolutions** [comment]
@dteoh It works fairly well for me.

1. There is a minor flickering issue if I:

- Press Cmd-Q
- Before the circle fills, release Q (but keep holding down Cmd)
- Press Q again

It works normally if I also release Cmd, and then press Cmd-Q.

2. The circle also starts filling in when I quit items from the Cmd-Tab menu, even though it does not actually slow down the quit action. A little jarring, but no different from previous versions other than the animation showing.

One confusing thing, perhaps due to Homebrew Cask, was that the app wanted Accessibility permissions again after being updated. But in Accessibility, it was already there. I just pressed the `+` and re-selected it from `/Applications`. I don't know if I even needed to do that. Anyway, it worked.

**Comment by wizonesolutions** [comment]
It's not crashing, but I noticed a new issue where after quitting an app with Cmd-Q, I can't close the Cmd-Tab menu with the Esc key anymore. I have to click out of it with the mouse.

**Comment by dteoh** [comment]
> The circle also starts filling in when I quit items from the Cmd-Tab menu, even though it does not actually slow down the quit action. A little jarring, but no different from previous versions other than the animation showing.

> It's not crashing, but I noticed a new issue where after quitting an app with Cmd-Q, I can't close the Cmd-Tab menu with the Esc key anymore. I have to click out of it with the mouse.

Will be fixed as part of #55.
