### ISSUE TITLE
shouldHandleCmdQ(): check for Finder Quit menu command

### ISSUE THREAD

**Issue by JayBrown** [dteoh/SlowQuitApps#50]
Some users (like me) have added the Quit menu command to Finder.

SQA is currently not handling Finder at all.

However, you could read the keyPath `QuitMenuItem` from `\(NSHomeDirectory())/Library/Preferences/com.apple.finder.plist`, and if the returned value is 1 (BOOL true), then `BOOL shouldHandleCmdQ()` in `SQAAppDelegate.m` should return "YES" for Bundle ID `com.apple.finder`, in all other cases it would be "NO", as it is now.

Possible?

**Comment by dteoh** [comment]
I'm not really sure what behaviour you have implemented, but at least in issue #4, being able to quit the Finder did a lot more than expected, so Finder is currently hardcoded to be ignored by SQA.

SQA is probably not going to start reading custom preference files of the active app to determine if the Cmd-Q slowdown can trigger (need to determine whether Cmd-Q is an actual shortcut that can be activated by the target app, otherwise the progress bar is rendered).

**Comment by dteoh** [comment]
Will not be addressed.
